# Generated by Django 5.0.6 on 2024-06-10 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('prediction', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('url', models.URLField()),
                ('image_name', models.CharField(blank=True, max_length=255, null=True)),
                ('original_width', models.IntegerField(blank=True, null=True)),
                ('original_height', models.IntegerField(blank=True, null=True)),
                ('model_width', models.IntegerField(blank=True, null=True)),
                ('model_height', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
